import type { Route, Tone } from "./generator";

export type AdditionalLanguage = "Русский" | "中文（简体）" | "Bahasa Indonesia" | "日本語" | "한국어" | "ไทย" | "Tiếng Việt" | "Bahasa Melayu" | "العربية";

export const additionalLanguages: AdditionalLanguage[] = ["Русский","中文（简体）","Bahasa Indonesia","日本語","한국어","ไทย","Tiếng Việt","Bahasa Melayu","العربية"];

const issue: Record<AdditionalLanguage,Record<string,string>> = {
  "Русский":{"Pay-to-win / cost":"стоимость и pay-to-win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"подбор соперников","Power creep":"постоянный рост силы","Heroes and catch-up":"герои и механики догоняющего прогресса","Event rewards":"награды за события","Game complexity":"сложность игры","Too many major updates":"слишком частые крупные обновления","Bugs / performance":"ошибки и производительность"},
  "中文（简体）":{"Pay-to-win / cost":"付费压力与 Pay-to-Win","Armaments / Weapon Transcendence":"武装与 Weapon Transcendence","Matchmaking":"匹配机制","Power creep":"战力膨胀","Heroes and catch-up":"英雄与追赶机制","Event rewards":"活动奖励","Game complexity":"游戏系统过于复杂","Too many major updates":"大型更新过于频繁","Bugs / performance":"Bug 与性能问题"},
  "Bahasa Indonesia":{"Pay-to-win / cost":"biaya dan pay-to-win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"matchmaking","Power creep":"power creep","Heroes and catch-up":"hero dan mekanisme catch-up","Event rewards":"hadiah event","Game complexity":"kompleksitas game","Too many major updates":"terlalu banyak update besar","Bugs / performance":"bug dan performa"},
  "日本語":{"Pay-to-win / cost":"課金負担とPay-to-Win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"マッチメイキング","Power creep":"パワークリープ","Heroes and catch-up":"ヒーローと追いつき要素","Event rewards":"イベント報酬","Game complexity":"ゲームの複雑化","Too many major updates":"大型アップデートの多さ","Bugs / performance":"不具合とパフォーマンス"},
  "한국어":{"Pay-to-win / cost":"과금 부담과 Pay-to-Win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"매치메이킹","Power creep":"파워 크리프","Heroes and catch-up":"영웅과 따라잡기 시스템","Event rewards":"이벤트 보상","Game complexity":"게임의 복잡성","Too many major updates":"너무 잦은 대형 업데이트","Bugs / performance":"버그와 성능"},
  "ไทย":{"Pay-to-win / cost":"ค่าใช้จ่ายและ Pay-to-Win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"การจับคู่","Power creep":"พลังที่เพิ่มขึ้นต่อเนื่อง","Heroes and catch-up":"ฮีโร่และระบบไล่ตาม","Event rewards":"รางวัลกิจกรรม","Game complexity":"ความซับซ้อนของเกม","Too many major updates":"อัปเดตใหญ่ถี่เกินไป","Bugs / performance":"บั๊กและประสิทธิภาพ"},
  "Tiếng Việt":{"Pay-to-win / cost":"chi phí và pay-to-win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"ghép trận","Power creep":"lạm phát sức mạnh","Heroes and catch-up":"tướng và cơ chế bắt kịp","Event rewards":"phần thưởng sự kiện","Game complexity":"độ phức tạp của game","Too many major updates":"quá nhiều cập nhật lớn","Bugs / performance":"lỗi và hiệu năng"},
  "Bahasa Melayu":{"Pay-to-win / cost":"kos dan pay-to-win","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"padanan pemain","Power creep":"peningkatan kuasa berterusan","Heroes and catch-up":"hero dan mekanisme mengejar","Event rewards":"ganjaran acara","Game complexity":"kerumitan permainan","Too many major updates":"terlalu banyak kemas kini besar","Bugs / performance":"pepijat dan prestasi"},
  "العربية":{"Pay-to-win / cost":"التكلفة ونظام الدفع للفوز","Armaments / Weapon Transcendence":"Armaments / Weapon Transcendence","Matchmaking":"نظام المطابقة","Power creep":"التضخم المستمر في القوة","Heroes and catch-up":"الأبطال وآليات اللحاق","Event rewards":"مكافآت الفعاليات","Game complexity":"تعقيد اللعبة","Too many major updates":"كثرة التحديثات الكبيرة","Bugs / performance":"الأخطاء والأداء"}
};

const toneLine: Record<AdditionalLanguage,Record<Tone,string>> = {
  "Русский":{calm:"Пишу это конструктивно, потому что хочу, чтобы игра оставалась здоровой в долгосрочной перспективе.",firm:"Ситуация требует реальных изменений — игрокам всё труднее оправдывать дальнейшие траты времени и денег.",emotional:"Говорить это неприятно, потому что игра и сообщество мне всё ещё дороги, но становится всё сложнее верить, что наши усилия действительно ценятся."},
  "中文（简体）":{calm:"我希望以建设性的方式反馈，因为我真心希望游戏能够长期健康发展。",firm:"目前的方向需要真正改变，否则玩家会越来越难以继续投入时间和金钱。",emotional:"我仍然在乎这款游戏和这里的朋友，所以看到自己的时间和努力越来越像在贬值，真的很令人失望。"},
  "Bahasa Indonesia":{calm:"Saya menyampaikan ini secara konstruktif karena saya ingin game ini tetap sehat dalam jangka panjang.",firm:"Situasi saat ini membutuhkan perubahan nyata; makin sulit membenarkan waktu dan uang yang terus dikeluarkan.",emotional:"Saya masih peduli pada game dan komunitas ini, jadi rasanya mengecewakan ketika waktu dan usaha pemain terasa makin tidak dihargai."},
  "日本語":{calm:"このゲームが長く健全に続いてほしいので、建設的な意見として伝えます。",firm:"現状は実際の改善が必要です。このままでは時間や課金を続ける理由が弱くなっていきます。",emotional:"今でもこのゲームや仲間が大切だからこそ、積み重ねてきた時間や努力の価値が薄れていくように感じるのがつらいです。"},
  "한국어":{calm:"게임이 장기적으로 건강하게 유지되길 바라며 건설적인 의견을 드립니다.",firm:"현재 방향은 실질적인 변화가 필요합니다. 지금 상태에서는 계속 시간과 돈을 투자하기 점점 어려워집니다.",emotional:"아직도 이 게임과 커뮤니티를 아끼기 때문에, 쌓아온 시간과 노력이 점점 가치 없게 느껴지는 것이 더 답답합니다."},
  "ไทย":{calm:"ผม/ฉันอยากเสนอความคิดเห็นอย่างสร้างสรรค์ เพราะอยากให้เกมเติบโตอย่างยั่งยืนในระยะยาว",firm:"สถานการณ์ตอนนี้ต้องมีการเปลี่ยนแปลงจริงจัง เพราะผู้เล่นยิ่งรู้สึกยากที่จะลงทุนเวลาและเงินต่อไป",emotional:"ยังรักเกมและชุมชนนี้อยู่ จึงยิ่งรู้สึกผิดหวังเมื่อเวลาและความพยายามที่สะสมมาดูเหมือนมีค่าน้อยลง"},
  "Tiếng Việt":{calm:"Tôi góp ý với tinh thần xây dựng vì muốn trò chơi phát triển lành mạnh lâu dài.",firm:"Tình hình hiện tại cần thay đổi thực sự; người chơi ngày càng khó biện minh cho việc tiếp tục bỏ thêm thời gian và tiền bạc.",emotional:"Tôi vẫn quan tâm đến game và cộng đồng này, nên càng buồn khi thời gian và công sức đã bỏ ra dường như ngày càng mất giá trị."},
  "Bahasa Melayu":{calm:"Saya berkongsi maklum balas ini secara membina kerana saya mahu permainan ini kekal sihat untuk jangka panjang.",firm:"Keadaan sekarang memerlukan perubahan sebenar; semakin sukar untuk pemain terus mewajarkan masa dan wang yang dilaburkan.",emotional:"Saya masih sayangkan permainan dan komuniti ini, jadi amat mengecewakan apabila masa dan usaha pemain terasa semakin kurang bernilai."},
  "العربية":{calm:"أشارك هذا الرأي بشكل بنّاء لأنني أريد للعبة أن تبقى صحية ومستدامة على المدى الطويل.",firm:"الوضع الحالي يحتاج إلى تغيير حقيقي، فقد أصبح من الصعب أكثر فأكثر تبرير الاستمرار في استثمار الوقت والمال.",emotional:"ما زلت أهتم باللعبة وبالمجتمع، ولذلك من المحبط أن أشعر بأن الوقت والجهد اللذين استثمرهما اللاعبون يفقدان قيمتهما تدريجياً."}
};

export function additionalDraft(language:AdditionalLanguage, route:Route, tone:Tone, ctx:{issue:string; impact:string; love:string; playerType:string; years:string; platform:string}){
  const topic=issue[language][ctx.issue]||ctx.issue;
  const lead=toneLine[language][tone];
  const years=ctx.years.trim();
  const p=ctx.playerType;
  if(language==="Русский"){
    if(route==="email") return `${lead}\n\n${years?`Я играю около ${years} лет и отношу себя к категории ${p}. `:""}Меня до сих пор удерживают в игре ${ctx.love}.\n\nБольше всего меня сейчас беспокоит ${topic}. Для меня это означает: ${ctx.impact}.\n\nЯ не прошу сделать всё бесплатным. Я прошу IGG пересмотреть эту систему и сделать прогресс и конкуренцию более устойчивыми для обычных игроков.\n\nПожалуйста, прислушайтесь к игрокам, которые говорят об этом именно потому, что хотят видеть игру лучше.`;
    if(route==="discord") return `${lead} Хочу обсудить ${topic}. Для меня ${ctx.impact}. Я всё ещё здесь из-за ${ctx.love}, но считаю, что IGG должна серьёзно пересмотреть эту систему. Что думаете вы?`;
    if(route==="public") return `${lead}\n\n${topic} всё сильнее мешает оставаться вовлечённым. ${ctx.impact}. IGG, пожалуйста, прислушайтесь к игрокам и пересмотрите этот подход. Мы хотим более здоровую игру, а не бесплатную.\n\n#PlayersFirst #DoomsdayLastSurvivors`;
    if(route==="video") return `ХУК\n${lead}\n\nСЦЕНАРИЙ\nМоя главная проблема сейчас — ${topic}. ${ctx.impact}. Я не прошу сделать всё бесплатным. Я хочу, чтобы IGG сделала прогресс более устойчивым и справедливым. Я говорю об этом, потому что мне всё ещё важна игра.`;
    return `БРИФ ДЛЯ АВТОРА — ${topic.toUpperCase()}\n\nТОН\n${lead}\n\nТЕЗИС\nМонетизация допустима, но игроки должны верить, что их время, усилия и траты сохраняют ценность.\n\nКЛЮЧЕВЫЕ ПУНКТЫ\n• Что удерживает игроков: ${ctx.love}.\n• Влияние: ${ctx.impact}.\n• Требование: пересмотреть систему и сделать прогресс устойчивее.\n• Не преувеличивать: отделять личный опыт, оценки сообщества и проверенные факты.\n\nCTA\nРасскажите о своём опыте своими словами. Одно сообщество. Много голосов.`;
  }
  const common: Record<Exclude<AdditionalLanguage,"Русский">,{email:string;discord:string;public:string;video:string;creator:string}> = {
    "中文（简体）":{email:`${lead}\n\n${years?`我大约玩了 ${years} 年，属于 ${p}。`:""}让我继续留下来的，是 ${ctx.love}。\n\n我目前最担心的是${topic}。对我来说，${ctx.impact}。\n\n我不是要求游戏完全免费。我希望 IGG 重新审视这个问题，让普通玩家的成长与竞争更加可持续。\n\n请认真听取那些因为仍然在乎这款游戏而发声的玩家。`,discord:`${lead} 想和大家讨论一下${topic}。对我来说，${ctx.impact}。我仍然因为 ${ctx.love} 留在这里，但我认为 IGG 应该认真重新审视这个系统。大家怎么看？`,public:`${lead}\n\n${topic}正越来越影响玩家继续投入。${ctx.impact}。IGG，请听取玩家意见并重新审视这个系统。我们想要的是更健康的游戏，而不是免费的游戏。\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`开场\n${lead}\n\n脚本\n我目前最担心的是${topic}。${ctx.impact}。我不是要求一切免费，而是希望 IGG 让成长和竞争更加可持续。我愿意发声，是因为我仍然在乎这款游戏。`,creator:`创作者简报 — ${topic}\n\n核心观点\n玩家可以接受商业化，但需要相信自己的时间、努力和付费仍然有长期价值。\n\n重点\n• 玩家仍然珍惜：${ctx.love}\n• 影响：${ctx.impact}\n• 诉求：重新审视系统，让成长更加可持续\n• 不要夸大：区分个人体验、社区估算和已验证事实\n\n行动号召\n用你自己的话分享你的真实体验。一个社区，多种声音。`},
    "Bahasa Indonesia":{email:`${lead}\n\n${years?`Saya sudah bermain sekitar ${years} tahun sebagai ${p}. `:""}Yang masih membuat saya bertahan adalah ${ctx.love}.\n\nKekhawatiran terbesar saya saat ini adalah ${topic}. Bagi saya, ${ctx.impact}.\n\nSaya tidak meminta semuanya gratis. Saya meminta IGG meninjau sistem ini dan membuat progres serta kompetisi lebih berkelanjutan bagi pemain biasa.`,discord:`${lead} Saya ingin membahas ${topic}. Bagi saya, ${ctx.impact}. Saya masih bertahan karena ${ctx.love}, tetapi IGG perlu meninjau sistem ini dengan serius. Bagaimana menurut kalian?`,public:`${lead}\n\n${topic} makin menyulitkan pemain untuk tetap berinvestasi. ${ctx.impact}. IGG, tolong dengarkan pemain dan tinjau kembali sistem ini. Kami ingin game yang lebih sehat, bukan game gratis.\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`HOOK\n${lead}\n\nSCRIPT\nKekhawatiran terbesar saya adalah ${topic}. ${ctx.impact}. Saya tidak meminta semuanya gratis. Saya ingin IGG membuat progres lebih berkelanjutan dan seimbang. Saya bicara karena saya masih peduli pada game ini.`,creator:`BRIEF KREATOR — ${topic.toUpperCase()}\n\nTESIS\nPemain dapat menerima monetisasi, tetapi harus percaya bahwa waktu, usaha, dan pengeluaran tetap memiliki nilai.\n\nPOIN UTAMA\n• Yang masih kami hargai: ${ctx.love}\n• Dampak: ${ctx.impact}\n• Permintaan: tinjau sistem dan buat progres lebih berkelanjutan\n• Jangan berlebihan: bedakan pengalaman pribadi, perkiraan komunitas, dan fakta terverifikasi.\n\nCTA\nBagikan pengalamanmu dengan kata-katamu sendiri. Satu komunitas. Banyak suara.`},
    "日本語":{email:`${lead}\n\n${years?`約${years}年間プレイしており、${p}です。`:""}今も続けている理由は ${ctx.love} です。\n\n現在もっとも気になっているのは${topic}です。私にとっては、${ctx.impact}。\n\nすべてを無料にしてほしいわけではありません。IGGにはこの仕組みを見直し、一般プレイヤーにも持続可能な成長と競争環境を作ってほしいです。`,discord:`${lead} ${topic}についてみんなの意見を聞きたいです。私にとっては${ctx.impact}。${ctx.love}があるから続けていますが、IGGにはこの仕組みを真剣に見直してほしいです。皆さんはどう感じていますか？`,public:`${lead}\n\n${topic}によって、時間やお金を投資し続けることが難しくなっています。${ctx.impact}。IGGにはプレイヤーの声を聞き、この仕組みを見直してほしいです。無料ゲームを求めているのではなく、より健全なゲームを求めています。\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`フック\n${lead}\n\nスクリプト\n今一番気になっているのは${topic}です。${ctx.impact}。すべてを無料にしてほしいのではなく、IGGにもっと持続可能でバランスの取れた成長環境を作ってほしいです。`,creator:`クリエイターブリーフ — ${topic}\n\n主張\n課金は受け入れられても、時間・努力・課金の価値が長く残るという信頼が必要です。\n\n要点\n• 今も大切にしているもの：${ctx.love}\n• 影響：${ctx.impact}\n• 要望：仕組みを見直し、持続可能な成長にする\n• 誇張しない：個人の体験、コミュニティの推定、確認済みの事実を分ける\n\nCTA\n自分の経験を自分の言葉で共有してください。ひとつのコミュニティ、多くの声。`},
    "한국어":{email:`${lead}\n\n${years?`약 ${years}년 동안 플레이했고 ${p}입니다. `:""}제가 아직 게임을 계속하는 이유는 ${ctx.love}입니다.\n\n현재 가장 큰 걱정은 ${topic}입니다. 저에게는 ${ctx.impact}.\n\n모든 것을 무료로 해달라는 것이 아닙니다. IGG가 이 시스템을 재검토하고 일반 플레이어도 지속 가능한 성장과 경쟁을 할 수 있게 해주길 바랍니다.`,discord:`${lead} ${topic}에 대해 이야기해보고 싶습니다. 저에게는 ${ctx.impact}. 아직 ${ctx.love} 때문에 게임을 하고 있지만, IGG가 이 시스템을 진지하게 재검토해야 한다고 생각합니다. 여러분은 어떻게 느끼시나요?`,public:`${lead}\n\n${topic} 때문에 계속 시간과 돈을 투자하기가 점점 어려워지고 있습니다. ${ctx.impact}. IGG가 플레이어의 목소리를 듣고 이 시스템을 다시 검토해주길 바랍니다. 무료 게임을 원하는 것이 아니라 더 건강한 게임을 원합니다.\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`훅\n${lead}\n\n스크립트\n현재 가장 큰 걱정은 ${topic}입니다. ${ctx.impact}. 모든 것을 무료로 원하는 것이 아닙니다. IGG가 더 지속 가능하고 균형 잡힌 성장 구조를 만들어주길 바랍니다.`,creator:`크리에이터 브리프 — ${topic}\n\n핵심 주장\n과금 자체는 받아들일 수 있지만, 플레이어는 시간·노력·지출의 가치가 오래 유지된다는 신뢰가 필요합니다.\n\n핵심 포인트\n• 여전히 소중한 것: ${ctx.love}\n• 영향: ${ctx.impact}\n• 요청: 시스템 재검토와 지속 가능한 성장\n• 과장 금지: 개인 경험, 커뮤니티 추정, 검증된 사실을 구분\n\nCTA\n자신의 경험을 자신의 말로 공유하세요. 하나의 커뮤니티, 많은 목소리.`},
    "ไทย":{email:`${lead}\n\n${years?`เล่นมาประมาณ ${years} ปี และเป็น ${p} `:""}สิ่งที่ยังทำให้อยู่กับเกมคือ ${ctx.love}\n\nสิ่งที่กังวลที่สุดตอนนี้คือ ${topic} สำหรับผม/ฉัน ${ctx.impact}\n\nไม่ได้ขอให้ทุกอย่างฟรี แต่อยากให้ IGG ทบทวนระบบนี้และทำให้การพัฒนาและการแข่งขันยั่งยืนขึ้นสำหรับผู้เล่นทั่วไป`,discord:`${lead} อยากคุยเรื่อง ${topic} สำหรับผม/ฉัน ${ctx.impact} ยังเล่นอยู่เพราะ ${ctx.love} แต่คิดว่า IGG ควรทบทวนระบบนี้อย่างจริงจัง ทุกคนรู้สึกอย่างไรบ้าง?`,public:`${lead}\n\n${topic} ทำให้ยากขึ้นเรื่อย ๆ ที่จะลงทุนเวลาและเงินต่อไป ${ctx.impact} IGG โปรดรับฟังผู้เล่นและทบทวนระบบนี้ เราต้องการเกมที่สุขภาพดีขึ้น ไม่ใช่เกมฟรี\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`HOOK\n${lead}\n\nSCRIPT\nสิ่งที่กังวลที่สุดคือ ${topic} ${ctx.impact} ไม่ได้ขอให้ทุกอย่างฟรี แต่อยากให้ IGG ทำให้ระบบพัฒนาและการแข่งขันยั่งยืนและสมดุลมากขึ้น`,creator:`CREATOR BRIEF — ${topic}\n\nประเด็นหลัก\nผู้เล่นยอมรับการสร้างรายได้ได้ แต่ต้องมั่นใจว่าเวลา ความพยายาม และเงินที่ใช้ยังคงมีคุณค่า\n\nหัวข้อสำคัญ\n• สิ่งที่ยังมีคุณค่า: ${ctx.love}\n• ผลกระทบ: ${ctx.impact}\n• ข้อเสนอ: ทบทวนระบบและทำให้การพัฒนายั่งยืนขึ้น\n• อย่าพูดเกินจริง: แยกประสบการณ์ส่วนตัว การประเมินของชุมชน และข้อเท็จจริงที่ตรวจสอบแล้ว\n\nCTA\nแชร์ประสบการณ์ของคุณด้วยคำพูดของคุณเอง หนึ่งชุมชน หลายเสียง`},
    "Tiếng Việt":{email:`${lead}\n\n${years?`Tôi đã chơi khoảng ${years} năm và thuộc nhóm ${p}. `:""}Điều khiến tôi vẫn tiếp tục là ${ctx.love}.\n\nMối lo lớn nhất hiện nay là ${topic}. Với tôi, ${ctx.impact}.\n\nTôi không yêu cầu mọi thứ phải miễn phí. Tôi mong IGG xem xét lại hệ thống này và tạo con đường phát triển, cạnh tranh bền vững hơn cho người chơi bình thường.`,discord:`${lead} Tôi muốn bàn về ${topic}. Với tôi, ${ctx.impact}. Tôi vẫn chơi vì ${ctx.love}, nhưng IGG cần nghiêm túc xem xét lại hệ thống này. Mọi người cảm thấy thế nào?`,public:`${lead}\n\n${topic} đang khiến việc tiếp tục đầu tư thời gian và tiền bạc trở nên khó khăn hơn. ${ctx.impact}. IGG, hãy lắng nghe người chơi và xem xét lại hệ thống này. Chúng tôi muốn một game lành mạnh hơn, không phải một game miễn phí.\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`HOOK\n${lead}\n\nKỊCH BẢN\nMối lo lớn nhất của tôi là ${topic}. ${ctx.impact}. Tôi không yêu cầu mọi thứ miễn phí; tôi muốn IGG tạo một hệ thống phát triển bền vững và cân bằng hơn.`,creator:`BRIEF CHO CREATOR — ${topic.toUpperCase()}\n\nLUẬN ĐIỂM\nNgười chơi có thể chấp nhận kiếm tiền, nhưng cần tin rằng thời gian, công sức và tiền bạc của họ vẫn giữ được giá trị.\n\nĐIỂM CHÍNH\n• Điều vẫn đáng quý: ${ctx.love}\n• Tác động: ${ctx.impact}\n• Yêu cầu: xem xét lại hệ thống và tạo tiến trình bền vững\n• Không phóng đại: phân biệt trải nghiệm cá nhân, ước tính cộng đồng và dữ kiện đã xác minh\n\nCTA\nChia sẻ trải nghiệm của bạn bằng chính lời của bạn. Một cộng đồng. Nhiều tiếng nói.`},
    "Bahasa Melayu":{email:`${lead}\n\n${years?`Saya telah bermain kira-kira ${years} tahun sebagai ${p}. `:""}Apa yang masih membuat saya kekal ialah ${ctx.love}.\n\nKebimbangan terbesar saya sekarang ialah ${topic}. Bagi saya, ${ctx.impact}.\n\nSaya tidak meminta semuanya percuma. Saya mahu IGG menilai semula sistem ini dan menjadikan kemajuan serta persaingan lebih mampan untuk pemain biasa.`,discord:`${lead} Saya mahu bincangkan ${topic}. Bagi saya, ${ctx.impact}. Saya masih bermain kerana ${ctx.love}, tetapi saya rasa IGG perlu menilai semula sistem ini dengan serius. Apa pandangan semua?`,public:`${lead}\n\n${topic} semakin menyukarkan pemain untuk terus melabur masa dan wang. ${ctx.impact}. IGG, sila dengar suara pemain dan nilai semula sistem ini. Kami mahukan permainan yang lebih sihat, bukan permainan percuma.\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`HOOK\n${lead}\n\nSKRIP\nKebimbangan terbesar saya ialah ${topic}. ${ctx.impact}. Saya tidak meminta semuanya percuma. Saya mahu IGG menjadikan kemajuan lebih mampan dan seimbang.`,creator:`BRIEF PENCIPTA — ${topic.toUpperCase()}\n\nTESIS\nPemain boleh menerima monetisasi, tetapi perlu yakin bahawa masa, usaha dan perbelanjaan mereka kekal bernilai.\n\nPOIN UTAMA\n• Apa yang masih dihargai: ${ctx.love}\n• Kesan: ${ctx.impact}\n• Permintaan: nilai semula sistem dan wujudkan kemajuan mampan\n• Jangan berlebihan: bezakan pengalaman peribadi, anggaran komuniti dan fakta yang disahkan\n\nCTA\nKongsi pengalaman anda dengan kata-kata sendiri. Satu komuniti. Banyak suara.`},
    "العربية":{email:`${lead}\n\n${years?`ألعب منذ حوالي ${years} سنوات وأنا من فئة ${p}. `:""}ما زال يبقيني في اللعبة هو ${ctx.love}.\n\nأكبر ما يقلقني الآن هو ${topic}. بالنسبة لي، ${ctx.impact}.\n\nأنا لا أطلب أن يكون كل شيء مجانياً. أطلب من IGG مراجعة هذا النظام وجعل التقدم والمنافسة أكثر استدامة للاعبين العاديين.\n\nنحن نتحدث لأننا ما زلنا نهتم باللعبة ونريد لها أن تتحسن.`,discord:`${lead} أريد فتح نقاش حول ${topic}. بالنسبة لي، ${ctx.impact}. ما زلت هنا بسبب ${ctx.love}، لكنني أعتقد أن على IGG مراجعة هذا النظام بجدية. كيف ترون الأمر؟`,public:`${lead}\n\n${topic} يجعل الاستمرار في استثمار الوقت والمال أصعب. ${ctx.impact}. يا IGG، استمعوا إلى اللاعبين وراجعوا هذا النظام. نحن نريد لعبة أكثر صحة، لا لعبة مجانية.\n\n#PlayersFirst #DoomsdayLastSurvivors`,video:`مقدمة\n${lead}\n\nالنص\nأكبر ما يقلقني هو ${topic}. ${ctx.impact}. لا أطلب أن يكون كل شيء مجانياً؛ أريد من IGG أن تجعل التقدم أكثر استدامة وتوازناً. أتحدث لأن اللعبة ما زالت تهمني.`,creator:`موجز لصانع المحتوى — ${topic}\n\nالفكرة الرئيسية\nيمكن للاعبين تقبل تحقيق الأرباح، لكنهم يحتاجون إلى الثقة بأن وقتهم وجهدهم وإنفاقهم سيحتفظ بقيمته.\n\nالنقاط الرئيسية\n• ما زال اللاعبون يقدرونه: ${ctx.love}\n• التأثير: ${ctx.impact}\n• الطلب: مراجعة النظام وجعل التقدم أكثر استدامة\n• لا تبالغ: فرّق بين التجربة الشخصية وتقديرات المجتمع والحقائق المؤكدة\n\nالدعوة إلى العمل\nشارك تجربتك بكلماتك أنت. مجتمع واحد، أصوات كثيرة.`}
  };
  return common[language][route];
}
