export type SupportedLanguage = "English" | "Español" | "Português" | "Français" | "Deutsch";
export type LocalizedRoute = "email" | "discord" | "public" | "video" | "creator";

const issueMap: Record<Exclude<SupportedLanguage,"English">,Record<string,string>> = {
  Español: {
    "Pay-to-win / cost":"el coste y el pay-to-win","Armaments / Weapon Transcendence":"Armaments y Weapon Transcendence","Matchmaking":"el emparejamiento","Power creep":"el aumento constante de poder","Heroes and catch-up":"los héroes y los mecanismos para ponerse al día","Event rewards":"las recompensas de eventos","Game complexity":"la complejidad del juego","Too many major updates":"el ritmo de las grandes actualizaciones","Bugs / performance":"los errores y el rendimiento"
  },
  Português: {
    "Pay-to-win / cost":"o custo e o pay-to-win","Armaments / Weapon Transcendence":"Armaments e Weapon Transcendence","Matchmaking":"o matchmaking","Power creep":"o aumento constante de poder","Heroes and catch-up":"os heróis e os mecanismos de recuperação","Event rewards":"as recompensas dos eventos","Game complexity":"a complexidade do jogo","Too many major updates":"o ritmo das grandes atualizações","Bugs / performance":"os bugs e o desempenho"
  },
  Français: {
    "Pay-to-win / cost":"le coût et le pay-to-win","Armaments / Weapon Transcendence":"les Armaments et Weapon Transcendence","Matchmaking":"le matchmaking","Power creep":"l'escalade de puissance","Heroes and catch-up":"les héros et les mécanismes de rattrapage","Event rewards":"les récompenses d'événements","Game complexity":"la complexité du jeu","Too many major updates":"le rythme des mises à jour majeures","Bugs / performance":"les bugs et les performances"
  },
  Deutsch: {
    "Pay-to-win / cost":"Kosten und Pay-to-win","Armaments / Weapon Transcendence":"Armaments und Weapon Transcendence","Matchmaking":"Matchmaking","Power creep":"Power Creep","Heroes and catch-up":"Helden und Aufholmechanismen","Event rewards":"Event-Belohnungen","Game complexity":"die Komplexität des Spiels","Too many major updates":"das Tempo großer Updates","Bugs / performance":"Bugs und Performance"
  }
};

export function localizedDraft(language:SupportedLanguage, route:LocalizedRoute, ctx:{issue:string; impact:string; love:string; playerType:string; years:string; platform:string}){
  if(language==="English") return null;
  const issue=issueMap[language][ctx.issue] || ctx.issue;
  const years=ctx.years.trim();
  if(language==="Español"){
    if(route==="email") return `Escribo porque todavía me importa Doomsday: Last Survivors.\n\n${years?`Llevo aproximadamente ${years} años jugando y soy ${ctx.playerType}. `:""}Lo que todavía me mantiene en el juego es ${ctx.love}.\n\nMi principal preocupación ahora mismo es ${issue}. En mi caso, ${ctx.impact}.\n\nNo estoy pidiendo que todo sea gratis. Pido a IGG que revise este problema, reduzca las diferencias extremas y ofrezca una progresión más sostenible para jugadores normales.\n\nEspero que escuchen a los jugadores que hablan porque quieren que el juego mejore.`;
    if(route==="discord") return `Quería abrir una conversación sobre ${issue}. Para mí, ${ctx.impact}. Sigo aquí por ${ctx.love}, pero creo que IGG debería revisar este problema y ofrecer un camino más sostenible. ¿Cómo lo estáis viviendo vosotros?`;
    if(route==="public") return `${ctx.platform==="X"?"Sigo queriendo Doomsday, pero ":"Todavía me importa Doomsday: Last Survivors.\n\n"}${issue} está haciendo más difícil seguir invirtiendo tiempo y dinero. IGG, por favor escuchad a los jugadores y revisad este sistema. Queremos un juego más saludable, no un juego gratis.\n\n#PlayersFirst #DoomsdayLastSurvivors`;
    if(route==="video") return `GANCHO\nSigo jugando a Doomsday porque ${ctx.love}, pero me preocupa hacia dónde va el juego.\n\nGUION\nMi principal preocupación es ${issue}. Para mí, ${ctx.impact}. No pido que todo sea gratis. Pido a IGG un sistema más sostenible y equilibrado. Hablo porque todavía me importa el juego y quiero tener una razón para quedarme.`;
    return `BRIEF PARA CREADORES — ${issue.toUpperCase()}\n\nTESIS\nLos jugadores pueden aceptar la monetización, pero necesitan confiar en que su tiempo, esfuerzo y dinero mantendrán valor.\n\nPUNTOS CLAVE\n• Lo que todavía valoran los jugadores: ${ctx.love}.\n• Impacto: ${ctx.impact}.\n• Petición: revisar el sistema, reducir diferencias extremas y crear una progresión sostenible.\n• Enfoque justo: no es un mensaje contra quienes gastan dinero. F2P, pequeños gastadores y whales forman parte del mismo ecosistema.\n\nPRUEBAS A REUNIR\nCapturas del sistema, costes/requisitos, ejemplos antes/después y contexto real de guerra o eventos.\n\nNO EXAGERAR\nDistingue experiencias personales, estimaciones de la comunidad y hechos verificados.\n\nCTA\nCuenta tu propia experiencia con tus propias palabras. Una comunidad. Muchas voces.`;
  }
  if(language==="Português"){
    if(route==="email") return `Estou escrevendo porque ainda me importo com Doomsday: Last Survivors.\n\n${years?`Jogo há cerca de ${years} anos e sou ${ctx.playerType}. `:""}O que ainda me mantém no jogo é ${ctx.love}.\n\nMinha maior preocupação agora é ${issue}. Para mim, ${ctx.impact}.\n\nNão estou pedindo que tudo seja grátis. Peço à IGG que reveja esse problema, reduza diferenças extremas e ofereça uma progressão mais sustentável para jogadores comuns.\n\nEspero que escutem os jogadores que estão falando porque querem que o jogo melhore.`;
    if(route==="discord") return `Queria abrir uma conversa sobre ${issue}. Para mim, ${ctx.impact}. Ainda estou aqui por ${ctx.love}, mas acho que a IGG deveria rever esse problema e oferecer um caminho mais sustentável. Como vocês estão sentindo isso?`;
    if(route==="public") return `Ainda me importo com Doomsday: Last Survivors. ${issue} está tornando mais difícil continuar investindo tempo e dinheiro. IGG, por favor escute os jogadores e reveja esse sistema. Queremos um jogo mais saudável, não um jogo grátis. #PlayersFirst #DoomsdayLastSurvivors`;
    if(route==="video") return `GANCHO\nAinda jogo Doomsday por causa de ${ctx.love}, mas estou preocupado com a direção do jogo.\n\nROTEIRO\nMinha maior preocupação é ${issue}. Para mim, ${ctx.impact}. Não estou pedindo que tudo seja grátis. Quero que a IGG torne esse sistema mais sustentável e equilibrado. Estou falando porque ainda me importo com o jogo.`;
    return `BRIEF PARA CRIADORES — ${issue.toUpperCase()}\n\nTESE\nOs jogadores aceitam monetização, mas precisam confiar que tempo, esforço e dinheiro continuarão tendo valor.\n\nPONTOS-CHAVE\n• O que ainda valorizamos: ${ctx.love}.\n• Impacto: ${ctx.impact}.\n• Pedido: rever o sistema e criar uma progressão sustentável.\n• Enquadramento justo: isto não é contra quem gasta. F2P, pequenos gastadores e whales fazem parte do mesmo ecossistema.\n\nEVIDÊNCIAS\nMostre telas do jogo, custos/requisitos e contexto real de guerras ou eventos.\n\nNÃO EXAGERE\nSepare experiência pessoal, estimativas da comunidade e fatos verificados.\n\nCTA\nCompartilhe sua própria experiência com suas próprias palavras. Uma comunidade. Muitas vozes.`;
  }
  if(language==="Français"){
    if(route==="email") return `Je vous écris parce que Doomsday: Last Survivors compte encore pour moi.\n\n${years?`Je joue depuis environ ${years} ans et je suis ${ctx.playerType}. `:""}Ce qui me retient encore dans le jeu, c'est ${ctx.love}.\n\nMa principale inquiétude concerne ${issue}. Pour moi, ${ctx.impact}.\n\nJe ne demande pas que tout soit gratuit. Je demande à IGG de revoir ce problème, de réduire les écarts extrêmes et d'offrir une progression plus durable aux joueurs ordinaires.\n\nJ'espère que vous écouterez les joueurs qui s'expriment parce qu'ils veulent voir le jeu s'améliorer.`;
    if(route==="discord") return `Je voulais lancer une discussion sur ${issue}. Pour moi, ${ctx.impact}. Je reste grâce à ${ctx.love}, mais je pense qu'IGG devrait revoir ce problème et proposer une voie plus durable. Qu'en pensez-vous ?`;
    if(route==="public") return `Doomsday: Last Survivors compte encore pour moi, mais ${issue} rend l'investissement en temps et en argent de plus en plus difficile. IGG, écoutez les joueurs et revoyez ce système. Nous voulons un jeu plus sain, pas un jeu gratuit. #PlayersFirst #DoomsdayLastSurvivors`;
    if(route==="video") return `ACCROCHE\nJe joue encore à Doomsday grâce à ${ctx.love}, mais la direction du jeu m'inquiète.\n\nSCRIPT\nMa principale préoccupation est ${issue}. Pour moi, ${ctx.impact}. Je ne demande pas que tout soit gratuit. Je demande à IGG un système plus durable et équilibré. Je parle parce que ce jeu compte encore pour moi.`;
    return `BRIEF CRÉATEUR — ${issue.toUpperCase()}\n\nTHÈSE\nLes joueurs peuvent accepter la monétisation, mais ils doivent croire que leur temps, leurs efforts et leurs dépenses garderont de la valeur.\n\nPOINTS CLÉS\n• Ce que les joueurs apprécient encore : ${ctx.love}.\n• Impact : ${ctx.impact}.\n• Demande : revoir le système et créer une progression durable.\n• Cadre équitable : ce message n'est pas anti-dépense. F2P, petits dépensiers et whales font partie du même écosystème.\n\nPREUVES\nMontrez des captures du jeu, les coûts/conditions et le contexte réel des guerres ou événements.\n\nNE PAS EXAGÉRER\nDistinguez expérience personnelle, estimations communautaires et faits vérifiés.\n\nCTA\nPartagez votre propre expérience avec vos propres mots. Une communauté. Plusieurs voix.`;
  }
  if(route==="email") return `Ich schreibe, weil mir Doomsday: Last Survivors weiterhin wichtig ist.\n\n${years?`Ich spiele seit ungefähr ${years} Jahren und bin ${ctx.playerType}. `:""}Was mich weiterhin im Spiel hält, ist ${ctx.love}.\n\nMeine größte Sorge ist derzeit ${issue}. Für mich gilt: ${ctx.impact}.\n\nIch verlange nicht, dass alles kostenlos wird. Ich bitte IGG, dieses Problem zu überprüfen, extreme Unterschiede zu verringern und normalen Spielern einen nachhaltigeren Fortschrittsweg zu geben.\n\nBitte hören Sie den Spielern zu, die sich äußern, weil sie möchten, dass das Spiel besser wird.`;
  if(route==="discord") return `Ich möchte eine Diskussion über ${issue} anstoßen. Für mich gilt: ${ctx.impact}. Ich bin noch wegen ${ctx.love} dabei, aber ich denke, IGG sollte dieses Problem überprüfen und einen nachhaltigeren Weg schaffen. Wie erlebt ihr das?`;
  if(route==="public") return `Doomsday: Last Survivors ist mir weiterhin wichtig, aber ${issue} macht es schwieriger, weiter Zeit und Geld zu investieren. IGG: Bitte hört den Spielern zu und überprüft dieses System. Wir wollen ein gesünderes Spiel, kein kostenloses Spiel. #PlayersFirst #DoomsdayLastSurvivors`;
  if(route==="video") return `HOOK\nIch spiele Doomsday noch wegen ${ctx.love}, aber die Richtung des Spiels macht mir Sorgen.\n\nSCRIPT\nMeine größte Sorge ist ${issue}. Für mich gilt: ${ctx.impact}. Ich verlange nicht, dass alles kostenlos wird. Ich möchte, dass IGG dieses System nachhaltiger und ausgewogener macht. Ich spreche darüber, weil mir das Spiel noch wichtig ist.`;
  return `CREATOR-BRIEF — ${issue.toUpperCase()}\n\nTHESE\nSpieler können Monetarisierung akzeptieren, müssen aber darauf vertrauen können, dass Zeit, Aufwand und Ausgaben ihren Wert behalten.\n\nKERNPUNKTE\n• Was Spieler noch schätzen: ${ctx.love}.\n• Auswirkungen: ${ctx.impact}.\n• Forderung: System überprüfen und nachhaltigen Fortschritt schaffen.\n• Faire Einordnung: Dies ist nicht gegen zahlende Spieler. F2P, kleine Spender und Whales gehören zum selben Ökosystem.\n\nBELEGE\nZeige Screenshots, Kosten/Anforderungen sowie echten Kontext aus Kriegen oder Events.\n\nNICHT ÜBERTREIBEN\nTrenne persönliche Erfahrungen, Community-Schätzungen und verifizierte Fakten.\n\nCTA\nTeile deine eigene Erfahrung in deinen eigenen Worten. Eine Community. Viele Stimmen.`;
}
