import type { UILanguage } from "./uiTranslations";

export const personalization:Record<UILanguage,{types:{value:string;label:string}[];love:string;impact:string}>={
English:{types:[{value:"",label:"Prefer not to say"},{value:"F2P",label:"F2P"},{value:"low spender",label:"low spender"},{value:"moderate spender",label:"moderate spender"},{value:"heavy spender",label:"heavy spender"}],love:"the game, my alliance and the people I play with",impact:"the current direction is making progression feel less sustainable"},
Español:{types:[{value:"",label:"Prefiero no decirlo"},{value:"F2P",label:"F2P"},{value:"low spender",label:"gasto poco"},{value:"moderate spender",label:"gasto moderado"},{value:"heavy spender",label:"gasto mucho"}],love:"el juego, mi alianza y la gente con la que juego",impact:"la dirección actual hace que la progresión se sienta menos sostenible"},
Português:{types:[{value:"",label:"Prefiro não dizer"},{value:"F2P",label:"F2P"},{value:"low spender",label:"gasto pouco"},{value:"moderate spender",label:"gasto moderado"},{value:"heavy spender",label:"gasto alto"}],love:"o jogo, minha aliança e as pessoas com quem jogo",impact:"a direção atual está tornando a progressão menos sustentável"},
Français:{types:[{value:"",label:"Je préfère ne pas préciser"},{value:"F2P",label:"F2P"},{value:"low spender",label:"petit dépensier"},{value:"moderate spender",label:"dépensier modéré"},{value:"heavy spender",label:"gros dépensier"}],love:"le jeu, mon alliance et les personnes avec qui je joue",impact:"la direction actuelle rend la progression moins durable"},
Deutsch:{types:[{value:"",label:"Keine Angabe"},{value:"F2P",label:"F2P"},{value:"low spender",label:"kleiner Spender"},{value:"moderate spender",label:"mittlerer Spender"},{value:"heavy spender",label:"großer Spender"}],love:"das Spiel, meine Allianz und die Menschen, mit denen ich spiele",impact:"die aktuelle Richtung macht den Fortschritt weniger nachhaltig"},
Русский:{types:[{value:"",label:"Не указывать"},{value:"F2P",label:"F2P"},{value:"low spender",label:"небольшие траты"},{value:"moderate spender",label:"умеренные траты"},{value:"heavy spender",label:"крупные траты"}],love:"игра, мой альянс и люди, с которыми я играю",impact:"нынешнее направление делает развитие менее устойчивым"},
"中文（简体）":{types:[{value:"",label:"不填写"},{value:"F2P",label:"零氪玩家"},{value:"low spender",label:"低氪玩家"},{value:"moderate spender",label:"中度付费玩家"},{value:"heavy spender",label:"高付费玩家"}],love:"这款游戏、我的联盟和一起玩的伙伴",impact:"目前的方向让长期发展越来越难以持续"},
"Bahasa Indonesia":{types:[{value:"",label:"Tidak ingin menyebutkan"},{value:"F2P",label:"F2P"},{value:"low spender",label:"pengeluaran rendah"},{value:"moderate spender",label:"pengeluaran sedang"},{value:"heavy spender",label:"pengeluaran tinggi"}],love:"game ini, aliansi saya, dan orang-orang yang bermain bersama saya",impact:"arah saat ini membuat progres terasa semakin tidak berkelanjutan"},
日本語:{types:[{value:"",label:"回答しない"},{value:"F2P",label:"F2P"},{value:"low spender",label:"少額課金"},{value:"moderate spender",label:"中程度課金"},{value:"heavy spender",label:"高額課金"}],love:"このゲーム、同盟、そして一緒に遊ぶ仲間",impact:"現在の方向性では長期的な進行が続けにくくなっている"},
한국어:{types:[{value:"",label:"말하지 않음"},{value:"F2P",label:"F2P"},{value:"low spender",label:"소액 과금"},{value:"moderate spender",label:"중간 과금"},{value:"heavy spender",label:"고액 과금"}],love:"게임, 연맹, 그리고 함께 플레이하는 사람들",impact:"현재 방향 때문에 장기적인 성장이 지속 가능하지 않게 느껴집니다"},
ไทย:{types:[{value:"",label:"ไม่ระบุ"},{value:"F2P",label:"F2P"},{value:"low spender",label:"ใช้จ่ายน้อย"},{value:"moderate spender",label:"ใช้จ่ายปานกลาง"},{value:"heavy spender",label:"ใช้จ่ายสูง"}],love:"ตัวเกม พันธมิตร และเพื่อนที่เล่นด้วยกัน",impact:"ทิศทางปัจจุบันทำให้การพัฒนาระยะยาวรู้สึกไม่ยั่งยืน"},
"Tiếng Việt":{types:[{value:"",label:"Không muốn nói"},{value:"F2P",label:"F2P"},{value:"low spender",label:"chi ít"},{value:"moderate spender",label:"chi vừa"},{value:"heavy spender",label:"chi nhiều"}],love:"game, liên minh và những người tôi chơi cùng",impact:"hướng đi hiện tại khiến quá trình phát triển lâu dài kém bền vững hơn"},
"Bahasa Melayu":{types:[{value:"",label:"Tidak mahu nyatakan"},{value:"F2P",label:"F2P"},{value:"low spender",label:"belanja rendah"},{value:"moderate spender",label:"belanja sederhana"},{value:"heavy spender",label:"belanja tinggi"}],love:"permainan ini, pakatan saya dan rakan-rakan yang bermain bersama",impact:"hala tuju semasa menjadikan kemajuan jangka panjang kurang mampan"},
العربية:{types:[{value:"",label:"أفضل عدم التحديد"},{value:"F2P",label:"لاعب مجاني"},{value:"low spender",label:"إنفاق منخفض"},{value:"moderate spender",label:"إنفاق متوسط"},{value:"heavy spender",label:"إنفاق مرتفع"}],love:"اللعبة وتحالفي والأشخاص الذين ألعب معهم",impact:"الاتجاه الحالي يجعل التقدم طويل المدى أقل استدامة"}
};
